### ISSUE TITLE
Is the function "add_encoder_layer" in "seq2seq_ultimate.py" correct?

### ISSUE THREAD

**Issue by cdj0311** [zhedongzheng/finch#1]
Hi, I have a question:

Several code snippet in seq2seq_ultimate.py (function: add_encoder_layer"), maybe has an incorrect position:
bi_state_c = tf.concat((state_fw.c, state_bw.c), -1)
bi_state_h = tf.concat((state_fw.h, state_bw.h), -1)
bi_lstm_state = tf.nn.rnn_cell.LSTMStateTuple(c=bi_state_c, h=bi_state_h)
self.encoder_state = tuple([bi_lstm_state] * self.n_layers)

**Comment by zhedongzheng** [comment]
hi, cdj0311. This way works (as you can run the test), but i am not sure if it is the best way (or the most common way) to handle bi-directional LSTM state for encoder. If you have any suggestion, please let me know.

**Comment by zhedongzheng** [comment]
hi, cdj0311. What is the incorrect position?
I want to concat the state of forward cell and backward cell, do you mean this is incorrect?

**Comment by cdj0311** [comment]
@zhedongzheng I mean the variables "state_fw" and "state_bw" in the "for" loop, so 
bi_state_c = tf.concat((state_fw.c, state_bw.c), -1)
bi_state_h = tf.concat((state_fw.h, state_bw.h), -1)
should be in here too?

**Comment by zhedongzheng** [comment]
Hi, cdj0311. The for loop is used to control the multi-layers of bi-directional RNN. And I only want the latest "state_fw" and "state_bw" (latest means the last layer). Therefore, the final state is not put inside the for loop.

**Comment by cdj0311** [comment]
@zhedongzheng I see, thank you.
