### ISSUE TITLE
in vae code,how to use LSTMcell?

### ISSUE THREAD

**Issue by shaomai00** [zhedongzheng/finch#2]
when I change the GRUcell to LSTMcell ,I got this error:
ValueError: Shape must be rank 2 but is rank 3 for 'decoding/decoder/concat' (op: 'ConcatV2') with input shapes: [?,128], [2,?,20], [].

please help,
thanku~

**Comment by shaomai00** [comment]
and I see that in decoder init_state is transfer from z ,but what the concat_z means?

**Comment by zhedongzheng** [comment]
The story is that I want to concat z into decoder inputs (to let RNN keep using z). If I just pass into init_state, I am worried that RNN will quickly forgot it in decoding.

But the default decoder does not have the interface to let you concat z into inputs.
Therefore, i have modified the source code a bit to make this happen.

When you use LSTM instead of GRU, i think the problem is that LSTM has two states "h" and "c".
So I think you need to change this line
```
encoded_state = tf.concat((state_fw, state_bw), -1)
```
to
```
encoded_state = tf.concat((state_fw.h, state_bw.h), -1)
```
And also change this line
```
init_state = tf.layers.dense(self.z, args.rnn_size, tf.nn.elu)
```
to
```
state = tf.layers.dense(self.z, args.rnn_size, tf.nn.elu)
init_state = tf.contrib.rnn.LSTMStateTuple(c=state, h=state)
```

**Comment by shaomai00** [comment]
thank you very much! This kind of operation concat_z is just your idea or learned from other paper? Is there any source for the concat_z?

**Comment by zhedongzheng** [comment]
It comes from this paper (https://arxiv.org/pdf/1511.06349.pdf). The author has mentioned "including concatenating the sampled z to the decoder input at every time step" in Section 3.

**Comment by shaomai00** [comment]
thanku~ and after I edit these code as you said,it still appear some error:
 File "modified_tf_classes/beam_search_decoder.py", line 227, in __init__
    initial_state, self._cell.state_size)
...
ValueError: The two structures don't have the same number of elements.

First structure (1 elements): Tensor("decoding_1/tile_batch/Reshape:0", shape=(?, 128), dtype=float32)

Second structure (2 elements): LSTMStateTuple(c=128, h=128)

**Comment by zhedongzheng** [comment]
In the function _decoder_inference(), have you also changed:
```
with tf.variable_scope('decoding', reuse=True):
    init_state = tf.layers.dense(self.z, args.rnn_size, tf.nn.elu, reuse=True)
```
to
```
with tf.variable_scope('decoding', reuse=True):
    state = tf.layers.dense(self.z, args.rnn_size, tf.nn.elu, reuse=True)
init_state = tf.contrib.rnn.LSTMStateTuple(c=state, h=state)
```

**Comment by shaomai00** [comment]
it works,thank you very much ^^
