### ISSUE TITLE
beamsearch with attention mechanism

### ISSUE THREAD

**Issue by hastirad** [zhedongzheng/finch#3]
hi.
how can I add attention to ses2seq_beam?

**Comment by zhedongzheng** [comment]
In this [version](https://github.com/zhedongzheng/finch/blob/master/nlp-models/tensorflow/seq2seq_ultimate.py)
I have put bi-rnn encoder, attention, and beam-search together.
Do you mean removing the bi-rnn encoder, just want attention + beam-search?

**Comment by hastirad** [comment]
Thanks.
