### ISSUE TITLE
关于seq2seq_ultimate.py中attention复用的问题

### ISSUE THREAD

**Issue by HenryL-study** [zhedongzheng/finch#5]
HI，你好。
我最近在尝试复用seq2seq_ultimate.py中的代码，但是复用后在TensorBoard中发现train 和 infer 的attention结构没有复用，
即使是加了reuse = True之后也没有。
请您看看有没有这个问题呢~

**Comment by zhedongzheng** [comment]
您好，万分感谢您发现问题。
reuse = True 好像确实没用，由于这个问题（排序）设置得过于简单，之前没发现出来。
解决方法应该是把 decoder_cell 当作一个实例，生成一次就可以反复用了，没必要 reuse。
我这边正好再重新用 tf.estimator 接口重构以前的代码，我会尽快把 seq2seq 修复好。

**Comment by zhedongzheng** [comment]
[新版本的解决方案](https://github.com/zhedongzheng/finch/blob/master/nlp-models/tensorflow/tf-estimator/seq2seq_ultimate_test.ipynb)

**Comment by HenryL-study** [comment]
嗯嗯  好像是只能这样  我看Google官方实现也是分开来做的 Thanks~

**Comment by puqugithub** [comment]
@zhedongzheng 你好，“解决方法应该是把 decoder_cell 当作一个实例，生成一次就可以反复用了，没必要 reuse。”这个可以再解释一下吗？
