### ISSUE TITLE
VAE (RNN)  其中max_len设置200后会报错

### ISSUE THREAD

**Issue by zcqiand** [zhedongzheng/finch#8]
经过测试发现max_len长度超过读取数据的行数长度就会报错，不知道这个怎么解决？

还有读取数据量大的情况下会非常慢，这个怎么解决？

还有实例中的资料是英文的，可否针对中文的

**Comment by Kiteflyingee** [comment]
I also encountered this problem.I think the main problem is in this line of code.but i don't know how to fix it. - -!

![image](https://user-images.githubusercontent.com/12490322/54973075-54b9e300-4fc9-11e9-80e5-b41e7e83aa4f.png)

**Comment by zhedongzheng** [comment]
TF2 will replace TF1 in the near future, therefore I have to rewrite all the code.
Previous issues will be closed. Sorry for any inconvenience.
