### ISSUE TITLE
CBOW code

### ISSUE THREAD

**Issue by ZuoxiYang** [zhedongzheng/finch#9]
In the code of the "CBOW",
estimator.train(tf.estimator.inputs.numpy_input_fn(
    x_train, np.expand_dims(y_train, -1),
    batch_size = PARAMS['batch_size'],
    num_epochs = PARAMS['n_epochs'],
    shuffle = True))
when I run this codes, it reminded me that"Traceback (most recent call last):
  File "D:/pythonWorkSpace/AAB/tensorflow-CBOW.py", line 112, in <module>
    shuffle = True))
  File "E:\Anaconda\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\estimator\estimator.py", line 558, in _train_model
    features, labels = input_fn()
  File "E:\Anaconda\lib\site-packages\tensorflow\python\estimator\inputs\numpy_io.py", line 98, in input_fn
    raise TypeError('x must be dict; got {}'.format(type(x).__name__))
TypeError: x must be dict; got ndarray"
would you help me to solve the problem？ I have seen that you can run this code correctly.

**Comment by zhedongzheng** [comment]
Hi, there are indeed some problems.
I have updated the code, could you please update and try again?

**Comment by ZuoxiYang** [comment]
> Hi, there are indeed some problems.
> I have updated the code, could you please update and try again?

Thanks, it can work well now. And could tell me the reason about it?

**Comment by zhedongzheng** [comment]
Sure, in some old versions of TensorFlow, the input (x) of Estimator can be a numpy array; However, in new version of TensorFlow, it needs to be a dictionary. That is why you see "x must be dict; got ndarray"; If you have an array called ```x```, now you can change it to ```{'x': x}```;
